#auto: true # automatically update your jekyll
#server: true # runs a local server
paginate: 10 # pagination basted on number of posts
exclude: ["Gemfile", "Gemfile.lock", "README.md", 'sass', 'watch.sh', 'style.scss', 'vbc'] 
highlighter: rouge
markdown: kramdown
gems: [jekyll-paginate]